db.yumanyi.insertMany([
    {"_id": "Pel",
     "item": "Peluches", 
     "qty": 20, 
     "Marca": "Ty", 
     "Precio": 10, 
     "FechaEntrada":new Date("2020-12-1"),
     "Stock": true},
    {"_id": "FirAn", 
     "item": "FigurasAnimadas",  
     "qty": 15, 
     "Marca": "Banpresto", 
     "Precio": 24, 
     "FechaEntrada":new Date("2020-12-29"),
     "Stock": true},
    {"_id": "VidJue", 
     "item": "Videojuegos", 
     "qty": 45, 
     "Marca": ("EaSports, Activision, Sony, Microsoft"), 
     "Precio": 70, 
     "FechaEntrada":new Date("2020-12-15"),
     "Stock": true},
    {"_id": "VidCon", 
     "item": "Videoconsolas", 
     "qty": 0, 
     "Marca": ("PlayStation, Microsoft, Nintendo"), 
     "Precio": 400, 
     "FechaEntrada": new Date("2020-12-9"),
     "Stock": false},
    {"_id": "JueMes", 
     "item": "JuegosdeMesa", 
     "qty": 23, 
     "Marca": "Hasbro", 
     "Precio": 30, 
     "FechaEntrada": new Date("2020-12-15"),
     "Stock": true}])
